export const UI_ACTIONS = {
  UI_OPEN_MODAL: '[UI] OPEN MODAL',
  UI_CLOSE_MODAL: '[UI] CLOSE MODAL',
};

export const CALENDAR_ACTIONS = {
  CALENDAR_NEW_EVENT: '[CALENDAR] NEW EVENT',
  CALENDAR_ACTIVE_EVENT: '[CALENDAR] ACTIVE EVENT',
  CALENDAR_CLEAR_ACTIVE_EVENT: '[CALENDAR] CLEAR ACTIVE EVENT',
  CALENDAR_UPDATE_EVENT: '[CALENDAR] UPDATE EVENT',
  CALENDAR_DELETE_EVENT: '[CALENDAR] DELETE EVENT',
};
