export const UI_ACTIONS = {
  UI_OPEN_MODAL: '[UI] OPEN MODAL',
  UI_CLOSE_MODAL: '[UI] CLOSE MODAL',
};

export const CALENDAR_ACTIONS = {
  CALENDAR_NEW_EVENT: '[CALENDAR] NEW EVENT',
  CALENDAR_ACTIVE_EVENT: '[CALENDAR] ACTIVE EVENT',
  CALENDAR_CLEAR_ACTIVE_EVENT: '[CALENDAR] CLEAR ACTIVE EVENT',
  CALENDAR_UPDATE_EVENT: '[CALENDAR] UPDATE EVENT',
  CALENDAR_DELETE_EVENT: '[CALENDAR] DELETE EVENT',
};

export const AUTH_ACTIONS = {
  AUTH_START_CHECKING: '[AUTH] START CHECKING',
  AUTH_FINISH_CHECKING: '[AUTH] FINISH CHECKING',
  AUTH_START_LOGIN: '[AUTH] START LOGIN',
  AUTH_FINISH_LOGIN: '[AUTH] FINISH LOGIN',
  AUTH_START_REGISTER: '[AUTH] START RGISTR',
  AUTH_ON_TOKEN_RENEW: '[AUTH] ON TOKEN RENEW',
  AUTH_ON_LOGOUT: '[AUTH] ON LOGOUT',
};
