export const UI_ACTIONS = {
  UI_OPEN_MODAL: '[UI] OPEN MODAL',
  UI_CLOSE_MODAL: '[UI] CLOSE MODAL',
};

export const CALENDAR_ACTIONS = {
  CALENDAR_NEW_EVENT: '[CALENDAR] NEW EVENT',
  CALENDAR_ACTIVE_EVENT: '[CALENDAR] ACTIVE EVENT',
};
